name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/ci.yml
  deploy:
    name: Deploy app to AWS
    needs: [test] 
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install SSH key
        run: |
          mkdir -p -m 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/ec2-rails-deploy
          chmod 600 ~/.ssh/ec2-rails-deploy
          
      - name: Set SSH Config
        run: |
          cat << EOF > ~/.ssh/config
          Host ec2-rails-bastion
            StrictHostKeyChecking no
            HostName ${{ secrets.BASTION_HOSTNAME }}
          Host ec2-rails-web01
            ProxyJump deploy@ec2-rails-bastion
          Host ec2-rails-web02
            ProxyJump deploy@ec2-rails-bastion
          EOF

      - name: Deploy
        run: |
          eval $(ssh-agent)
          ssh-add ~/.ssh/ec2-rails-deploy
          bundle exec cap production deploy --trace
        env:
          CAP_WEB01: ec2-rails-web01
          CAP_WEB02: ec2-rails-web02